# SPDX-FileCopyrightText: 2020 CERN
# SPDX-FileCopyrightText: 2022 CERN (home.cern)
#
# SPDX-License-Identifier: LGPL-2.1-or-later

-include Makefile.specific

all:
clean:
install:
	python setup.py install

.PHONY: all clean install
