# SPDX-FileCopyrightText: 2020 CERN
# SPDX-FileCopyrightText: 2022 CERN (home.cern)
#
# SPDX-License-Identifier: CC0-1.0

-include Makefile.specific

all:
clean:
install:
	python setup.py install

.PHONY: all clean install
