---
# SPDX-FileCopyrightText: 2023 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

version: '1.0.0'
name: 'FMC Time to Digital Converter | FMC TDC 1ns 5cha'
description: 'https://raw.githubusercontent.com/wiki/vascoguita/fmc-tdc/Home.md'
website: 'https://ohwr.org/project/fmc-tdc'
licenses:
  - 'CC-BY-SA-4.0'
  - 'CERN-OHL-W-2.0'
  - 'GPL-2.0-or-later'
  - 'LGPL-2.1-or-later'
images:
  - 'https://ohwr.org/project/fmc-tdc/uploads/4b197628f86ba882512ac7639047bedc/EDA-02290-V2_Top.jpg'
  - 'https://ohwr.org/project/fmc-tdc/uploads/ac158eb4e90965e0ccbda0966e3326cf/CarriersWithTDC2.jpg'
  - 'https://ohwr.org/project/fmc-tdc/uploads/d42ed47b587c4d9a8b6790159f9b5b1b/TDC_TopView.png'
  - 'https://ohwr.org/project/fmc-tdc/uploads/a4b80f56b4bcb1b3929e9f2d6fb9c924/tdc_front.JPG'
  - 'https://ohwr.org/project/fmc-tdc/uploads/ac2a01312fd125340fa251ef969ec7f0/tdc_front-crop.JPG'
  - 'https://ohwr.org/project/fmc-tdc/uploads/4b197628f86ba882512ac7639047bedc/EDA-02290-V2_Top.jpg'
documentation: 'https://ohwr.org/project/fmc-tdc/wikis'
issues: 'https://ohwr.org/project/fmc-tdc/issues'
latest_release: 'https://ohwr.org/project/fmc-tdc/tags/v8.0.1'
forum: 'https://forums.ohwr.org/c/fmc-tdc'
newsfeed: 'https://raw.githubusercontent.com/wiki/vascoguita/fmc-tdc/News.md'
links:
  - name: 'v8 Performance'
    url: 'https://ohwr.org/project/fmc-tdc/wikis/uploads/83a32a976348f2c5484a470e68da0518/tdc_performance_report_v8.0.0.pdf'
  - name: 'v7 Hardware, Gateware and Software long runs on SVEC'
    url: 'https://www.ohwr.org/project/fmc-tdc/uploads/b08624193e2e48947a11708639d96921/LongRunsOnSVEC.pdf'
  - name: 'v7 TDC Precision'
    url: 'https://www.ohwr.org/project/fmc-tdc/uploads/a3b1bc0987d7cd2290d3394d73d835c8/TDCprecision.pdf'
  - name: 'v7 TDC Performance'
    url: 'https://www.ohwr.org/project/fmc-tdc/uploads/5bf6bf0a2d633382987f09a0915e20d8/TDCperformance.pdf'
  - name: 'How to set up the spec and fmc tdc with epics'
    url: 'https://ohwr.org/project/fmc-tdc/wikis/how-to-set-up-the-spec-and-fmc-tdc-with-epics'
