# SPDX-FileCopyrightText: 2022 CERN (home.cern)
#
# SPDX-License-Identifier: CC0-1.0

version: 2

submodules:
  recursive: false

python:
  version: 3.6
  install:
     - requirements: doc/requirements.txt

formats:
  - pdf
