/*
  Register definitions for slave core: GN4124 DMA enhanced interrupt controller

  * File           : /afs/cern.ch/user/f/fvaga/workspace-afs/projects/fmc-tdc/sources/fmc-tdc-sw/kernel/hw/tdc_dma_eic.h
  * Author         : auto-generated by wbgen2 from dma_eic.wb
  * Created        : Fri Aug 10 12:07:55 2018
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE dma_eic.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_DMA_EIC_WB
#define __WBGEN2_REGDEFS_DMA_EIC_WB

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <inttypes.h>
#endif

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Interrupt disable register */

/* definitions for field: DMA done interrupt in reg: Interrupt disable register */
#define DMA_EIC_EIC_IDR_DMA_DONE              WBGEN2_GEN_MASK(0, 1)

/* definitions for field: DMA error interrupt in reg: Interrupt disable register */
#define DMA_EIC_EIC_IDR_DMA_ERROR             WBGEN2_GEN_MASK(1, 1)

/* definitions for register: Interrupt enable register */

/* definitions for field: DMA done interrupt in reg: Interrupt enable register */
#define DMA_EIC_EIC_IER_DMA_DONE              WBGEN2_GEN_MASK(0, 1)

/* definitions for field: DMA error interrupt in reg: Interrupt enable register */
#define DMA_EIC_EIC_IER_DMA_ERROR             WBGEN2_GEN_MASK(1, 1)

/* definitions for register: Interrupt mask register */

/* definitions for field: DMA done interrupt in reg: Interrupt mask register */
#define DMA_EIC_EIC_IMR_DMA_DONE              WBGEN2_GEN_MASK(0, 1)

/* definitions for field: DMA error interrupt in reg: Interrupt mask register */
#define DMA_EIC_EIC_IMR_DMA_ERROR             WBGEN2_GEN_MASK(1, 1)

/* definitions for register: Interrupt status register */

/* definitions for field: DMA done interrupt in reg: Interrupt status register */
#define DMA_EIC_EIC_ISR_DMA_DONE              WBGEN2_GEN_MASK(0, 1)

/* definitions for field: DMA error interrupt in reg: Interrupt status register */
#define DMA_EIC_EIC_ISR_DMA_ERROR             WBGEN2_GEN_MASK(1, 1)
/* [0x20]: REG Interrupt disable register */
#define DMA_EIC_REG_EIC_IDR 0x00000000
/* [0x24]: REG Interrupt enable register */
#define DMA_EIC_REG_EIC_IER 0x00000004
/* [0x28]: REG Interrupt mask register */
#define DMA_EIC_REG_EIC_IMR 0x00000008
/* [0x2c]: REG Interrupt status register */
#define DMA_EIC_REG_EIC_ISR 0x0000000c
#endif
